name: Repository Settings

on:
  workflow_dispatch:
  push:
    paths:
      - .github/settings.yml

permissions:
  administration: write
  contents: read

jobs:
  apply-settings:
    name: Apply Settings
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Apply repository settings
        uses: peter-evans/repository-settings@v3
        with:
          token: ${{ secrets.REPO_ADMIN_TOKEN || github.token }}
          settings-file: .github/settings.yml
